{{- if and .Values.tls.enabled .Values.tls.certs.certManager.enabled }}
{{- if .Values.tls.certs.certManager.caProvided.enabled }}
apiVersion: keymaker.equinixmetal.com/v1
kind: ExternalSecretPull
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
  name: {{ template "cockroachdb.name" . }}-key-pair
spec:
  backend: ssm
  mappings:
    - key: /{{ .Values.clusterInfo.environment }}/{{ .Release.Namespace }}-ca-crt/{{ .Values.tls.certs.certManager.caProvided.version }}
      name: tls.crt
    - key: /{{ .Values.clusterInfo.environment }}/{{ .Release.Namespace }}/{{ .Release.Namespace }}-ca-key/{{ .Values.tls.certs.certManager.caProvided.version }}
      name: tls.key
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '0'
  # This is referenced from the upstream default values, plz no change me
  # https://github.com/cockroachdb/helm-charts/blob/c57245c47289153dd7c2f86bdc83ce7b1b6cab59/cockroachdb/values.yaml#L485
  name: {{ .Values.tls.certs.certManagerIssuer.name }}
spec:
  ca:
    secretName: {{ template "cockroachdb.name" . }}-key-pair
{{- end }}